"""initial_schema

Revision ID: c92ffa431b16
Revises: 
Create Date: 2026-09-15 11:02:03.935514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c92ffa431b16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_apis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=1024), nullable=False),
    sa.Column('endpoint_path', sa.String(length=1024), nullable=False),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'PATCH', 'DELETE', name='httpmethod', native_enum=False), nullable=False),
    sa.Column('is_sandbox', sa.Boolean(), nullable=False),
    sa.Column('test_payload', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('custom_headers', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('auth_type', sa.Enum('NONE', 'API_KEY', 'BEARER', 'BASIC', 'OAUTH2_CLIENT_CREDENTIALS', name='authtype', native_enum=False), nullable=False),
    sa.Column('auth_config', sa.Text(), nullable=True),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', name='apistatus', native_enum=False), nullable=False),
    sa.Column('rate_limit_header_limit', sa.String(length=100), nullable=True),
    sa.Column('rate_limit_header_remaining', sa.String(length=100), nullable=True),
    sa.Column('rate_limit_header_reset', sa.String(length=100), nullable=True),
    sa.Column('changelog_url', sa.String(length=1024), nullable=True),
    sa.Column('last_changelog_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracked_api_id', sa.Integer(), nullable=False),
    sa.Column('response_schema', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=False),
    sa.Column('headers_snapshot', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tracked_api_id'], ['tracked_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_snapshots_checked_at'), 'api_snapshots', ['checked_at'], unique=False)
    op.create_index(op.f('ix_api_snapshots_tracked_api_id'), 'api_snapshots', ['tracked_api_id'], unique=False)
    op.create_table('deprecation_notices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracked_api_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('notice_text', sa.Text(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tracked_api_id'], ['tracked_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deprecation_notices_detected_at'), 'deprecation_notices', ['detected_at'], unique=False)
    op.create_index(op.f('ix_deprecation_notices_tracked_api_id'), 'deprecation_notices', ['tracked_api_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracked_api_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'BREAKING', name='eventseverity', native_enum=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('old_value', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('new_value', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tracked_api_id'], ['tracked_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_severity'), 'events', ['severity'], unique=False)
    op.create_index(op.f('ix_events_tracked_api_id'), 'events', ['tracked_api_id'], unique=False)
    op.create_table('latency_baseline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracked_api_id', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=False),
    sa.Column('std_dev_ms', sa.Float(), nullable=False),
    sa.Column('error_rate_percent', sa.Float(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tracked_api_id'], ['tracked_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_latency_baseline_tracked_api_id'), 'latency_baseline', ['tracked_api_id'], unique=False)
    op.create_table('rate_limit_tracking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracked_api_id', sa.Integer(), nullable=False),
    sa.Column('limit_header_value', sa.Integer(), nullable=True),
    sa.Column('remaining_header_value', sa.Integer(), nullable=True),
    sa.Column('reset_header_value', sa.String(length=255), nullable=True),
    sa.Column('usage_percent', sa.Float(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tracked_api_id'], ['tracked_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_tracking_checked_at'), 'rate_limit_tracking', ['checked_at'], unique=False)
    op.create_index(op.f('ix_rate_limit_tracking_tracked_api_id'), 'rate_limit_tracking', ['tracked_api_id'], unique=False)
    op.create_table('schema_diffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracked_api_id', sa.Integer(), nullable=False),
    sa.Column('old_schema', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('new_schema', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('diff_summary', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('severity', sa.Enum('BREAKING', 'NON_BREAKING', 'INFORMATIONAL', name='diffseverity', native_enum=False), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tracked_api_id'], ['tracked_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_diffs_detected_at'), 'schema_diffs', ['detected_at'], unique=False)
    op.create_index(op.f('ix_schema_diffs_severity'), 'schema_diffs', ['severity'], unique=False)
    op.create_index(op.f('ix_schema_diffs_tracked_api_id'), 'schema_diffs', ['tracked_api_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schema_diffs_tracked_api_id'), table_name='schema_diffs')
    op.drop_index(op.f('ix_schema_diffs_severity'), table_name='schema_diffs')
    op.drop_index(op.f('ix_schema_diffs_detected_at'), table_name='schema_diffs')
    op.drop_table('schema_diffs')
    op.drop_index(op.f('ix_rate_limit_tracking_tracked_api_id'), table_name='rate_limit_tracking')
    op.drop_index(op.f('ix_rate_limit_tracking_checked_at'), table_name='rate_limit_tracking')
    op.drop_table('rate_limit_tracking')
    op.drop_index(op.f('ix_latency_baseline_tracked_api_id'), table_name='latency_baseline')
    op.drop_table('latency_baseline')
    op.drop_index(op.f('ix_events_tracked_api_id'), table_name='events')
    op.drop_index(op.f('ix_events_severity'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_deprecation_notices_tracked_api_id'), table_name='deprecation_notices')
    op.drop_index(op.f('ix_deprecation_notices_detected_at'), table_name='deprecation_notices')
    op.drop_table('deprecation_notices')
    op.drop_index(op.f('ix_api_snapshots_tracked_api_id'), table_name='api_snapshots')
    op.drop_index(op.f('ix_api_snapshots_checked_at'), table_name='api_snapshots')
    op.drop_table('api_snapshots')
    op.drop_table('tracked_apis')
    # ### end Alembic commands ###
